name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4-couch-mongo

    services:
      couchbase:
        image: couchbase:6.6.0
        ports:
          - 8091-8094:8091-8094
          - 11210:11210

    strategy:
      matrix:
        php: [ 7.3 ]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: PHP Install Dependencies (if not cached)
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest  --no-progress --prefer-dist

      - name: Couchbase - Initialize cluster
        run: |
          docker run --rm couchbase:6.6 couchbase-cli cluster-init -c 127.0.0.1 \
            --cluster-username Administrator \
            --cluster-password password \
            --services data,index,query \
            --cluster-ramsize 2048 \
            --cluster-index-ramsize 256

# Commented out for later usage in dream well
#      - name: Couchbase - Initialize cluster
#        run: |
#          php artisan couchbase:cluster:init
#
#      - name: Couchbase - Verify connection
#        run: |
#          php artisan couchbase:bucket:list
#
#      - name: Couchbase - Create bucket
#        run: |
#          php artisan couchbase:bucket:create --enable-flush=true
#
#      - name: Couchbase - Create primary index
#        run: |
#          php artisan couchbase:bucket:create-primary-index


      - name: Run Testsuite
        run: vendor/bin/phpunit
